### ISSUE TITLE
ゲームが開始したことをプレイヤーに明示する。

### ISSUE THREAD

**Issue by dsuz** [dsuz/punch-crash#1]
作業開始前に一度、「どのように作るか」を私と話し合ってください。
また、作業する際は、ブランチ名をここに書いてからやってください。

**Comment by Shiika89** [comment]
GameStartのテキストを表示するために、スクリプトのGameManagerで作業していきます。
ブランチ名は「game-start」です。

**Comment by Shiika89** [comment]
テキストを表示するときマスター側は正常に動作しているが、もう片方のテキストが正常に表示されないバグを修正中です
