### ISSUE TITLE
Deathzone の当たり判定の変更

### ISSUE THREAD

**Issue by dsuz** [dsuz/punch-crash#17]
Transform ではなく Rigidbody を使って動かしてください。
Collider ではなく Trigger で判定してください。
現状、同期していないのに Photon のコンポーネントを持っているので、同期させるか、Photon のコンポーネントは消してください。

**Comment by Ryuki-Machida** [comment]
以下の内容を修正しました。ブランチ名は「kill-wall-time」です。
TransformではなくRigidbodyを使って動かす。
Collider ではなく Trigger で判定する。
同期していないのに Photon のコンポーネントを持っているので、同期させるか、Photon のコンポーネントは消してください。

**Comment by ghost** [comment]
以下の内容を修正しました。ブランチ名は「Deathzone-wall」です。
Transform ではなく Rigidbody を使って動かしました。
Collider ではなく Trigger で判定しました。
Photon のコンポーネントを消しました。
