### ISSUE TITLE
プレイヤーがキャラクターを識別するために、プレイヤー1と2のキャラクターにそれぞれ異なる色を着ける。

### ISSUE THREAD

**Issue by dsuz** [dsuz/punch-crash#3]
作業開始前に一度、「どのように作るか」を私と話し合ってください。
また、作業する際は、ブランチ名をここに書いてからやってください。

**Comment by OnoueHiroaki** [comment]
プレイヤーの色を識別していくために、スクリプトのFighterControllerで作業していきます。
ブランチ名は「player-color-identification」です。

**Comment by OnoueHiroaki** [comment]
プレイヤーの色を変え識別できるようにしました。
ですが、自分が操作するキャラクターの色が変わるので、勝敗を決めた時が分かりづらいです。
