### ISSUE TITLE
背景画像を作り、スクロールする。

### ISSUE THREAD

**Issue by dsuz** [dsuz/punch-crash#4]
作業開始前に一度、「どのように作るか」を私と話し合ってください。
また、作業する際は、ブランチ名をここに書いてからやってください。

**Comment by teto0607** [comment]
背景をスクロールする作業をしていきます
ブランチ名は【background-scroll】です

**Comment by teto0607** [comment]
どんなテーマにするか決まってないので背景はまだ作ってはいませんがスクロール機能はできました
