### ISSUE TITLE
時間経過に伴い、下から迫ってくる「壁」を作る。

### ISSUE THREAD

**Issue by dsuz** [dsuz/punch-crash#5]
作業開始前に一度、「どのように作るか」を私と話し合ってください。
また、作業する際は、ブランチ名をここに書いてからやってください。

**Comment by Ryuki-Machida** [comment]
時間が経過したら、下から迫ってくる「壁」を作ります。
ブランチ名は kill-wall-timeです。

**Comment by ghost** [comment]
時間が経過したら、下から迫ってくる「壁」を作りました。
