### ISSUE TITLE
画面上（画面右上）に自分がプレイヤー１なのか２なのかを表示する

### ISSUE THREAD

**Issue by dsuz** [dsuz/punch-crash#9]
できれば、プレイヤーが3以上に増えた時のことも考慮して作ってほしいです。
作業開始前に一度、「どのように作るか」を私と話し合ってください。
また、作業する際は、ブランチ名をここに書いてからやってください。

**Comment by MomokoKita** [comment]
PS20Bの喜多桃子です。ブランチ名「Player-Name」として参加します。
